// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "!WQQOPOOO`OPO'#CaOOOO'#Cf'#CfOOOO'#Cd'#CdQQOPOOOOOO,58{,58{OqOPO,58{OOOO-E6b-E6bOOOO1G.g1G.g",
  stateData: "!S~OQQORQOSQOUPO~OQQORQOSQOUPOVTO~OQQORQOSQOUPOVWO~O",
  goto: "rZPPPPP[PPbPlXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ Program Identifier String Boolean Application ( )",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#T~RWrskst!Yxy!hyz!m!Q![!r!c!}!r#R#S!r#T#o!r~nTOrkrs}s#Ok#O#P!S#P~k~!SOR~~!VPO~k~!]Q#Y#Z!c#h#i!c~!hOS~~!mOU~~!rOV~~!wSQ~!Q![!r!c!}!r#R#S!r#T#o!r",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})

