name: prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npx prettier ./src/** .prettier.js .eslintrc.js .stylelintrc.js webpack.config.js --check
