name: stylelint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-styles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run lint:styles
